# Generated by tools.codegen. Do not edit.
from collections.abc import Awaitable, Callable
from functools import wraps
from importlib import import_module
from typing import Any

from fastapi import APIRouter
from fastapi.encoders import jsonable_encoder
from fastapi.responses import JSONResponse
from starlette.responses import Response

router = APIRouter()

type Handler = Callable[..., Awaitable[Any]]


def _with_response_codes(
    handler: Handler,
    response_codes: dict[type[Any], int],
) -> Callable[..., Awaitable[Response]]:
    @wraps(handler)
    async def endpoint(*args: Any, **kwargs: Any) -> Response:
        result = await handler(*args, **kwargs)
        if isinstance(result, Response):
            return result
        try:
            status_code = response_codes[type(result)]
        except KeyError:
            expected = ", ".join(model.__name__ for model in response_codes)
            raise TypeError(
                f"{handler.__module__}.{handler.__name__} returned "
                f"{type(result).__name__}; expected {expected} or Response"
            ) from None
        return JSONResponse(
            status_code=status_code,
            content=jsonable_encoder(result),
        )

    return endpoint

_handler = import_module('src.views.example_codegen.client.create_request')
_models = import_module('src.gen.example_codegen.api.client.create_request')
_RESPONSE_CODES_EXAMPLE_CODEGEN_CLIENT_CREATE_REQUEST = {
    _models.Response201: 201,
}
router.add_api_route(
    path='/example_codegen/client/create_request',
    endpoint=_with_response_codes(
        _handler.create_request,
        _RESPONSE_CODES_EXAMPLE_CODEGEN_CLIENT_CREATE_REQUEST,
    ),
    methods=['POST'],
    operation_id='example_codegen_client_create_request',
    summary=None,
    description=None,
    tags=['example_codegen'],
    deprecated=False,
    status_code=201,
    response_model=_models.Response201,
    responses={
        201: {
            "description": 'Заявка создана.',
            "model": _models.Response201,
        },
    },
)

_handler = import_module('src.views.example_codegen.client.get_request')
_models = import_module('src.gen.example_codegen.api.client.get_request')
_RESPONSE_CODES_EXAMPLE_CODEGEN_CLIENT_GET_REQUEST = {
    _models.Response200: 200,
    _models.Response404: 404,
}
router.add_api_route(
    path='/example_codegen/client/get_request',
    endpoint=_with_response_codes(
        _handler.get_request,
        _RESPONSE_CODES_EXAMPLE_CODEGEN_CLIENT_GET_REQUEST,
    ),
    methods=['GET'],
    operation_id='example_codegen_client_get_request',
    summary='Получить заявку',
    description='Возвращает заявку по идентификатору.',
    tags=['example_codegen'],
    deprecated=False,
    status_code=200,
    response_model=_models.Response200,
    responses={
        200: {
            "description": 'Заявка найдена.',
            "model": _models.Response200,
        },
        404: {
            "description": 'Заявки с таким идентификатором нет.',
            "model": _models.Response404,
        },
    },
)

_handler = import_module('src.views.images.get_next')
_models = import_module('src.gen.images.api.get_next')
_RESPONSE_CODES_IMAGES_GET_NEXT = {
    _models.Response200: 200,
    _models.Response404: 404,
}
router.add_api_route(
    path='/images/get_next',
    endpoint=_with_response_codes(
        _handler.get_next,
        _RESPONSE_CODES_IMAGES_GET_NEXT,
    ),
    methods=['GET'],
    operation_id='images_get_next',
    summary='Получить следующую картинку',
    description='Возвращает следующую картинку из упорядоченного циклического списка.',
    tags=['images'],
    deprecated=False,
    status_code=200,
    response_model=_models.Response200,
    responses={
        200: {
            "description": 'Следующая картинка найдена.',
            "model": _models.Response200,
        },
        404: {
            "description": 'В каталоге нет картинок.',
            "model": _models.Response404,
        },
    },
)

_handler = import_module('src.views.service.health')
_models = import_module('src.gen.service.api.health')
_RESPONSE_CODES_SERVICE_HEALTH = {
    _models.Response200: 200,
}
router.add_api_route(
    path='/service/health',
    endpoint=_with_response_codes(
        _handler.health,
        _RESPONSE_CODES_SERVICE_HEALTH,
    ),
    methods=['GET'],
    operation_id='service_health',
    summary='Проверить состояние сервиса',
    description='Возвращает успешный ответ, если HTTP-сервис работает.',
    tags=['service'],
    deprecated=False,
    status_code=200,
    response_model=_models.Response200,
    responses={
        200: {
            "description": 'Сервис работает.',
            "model": _models.Response200,
        },
    },
)
