"""Генерация моделей и шаблонов в памяти, без изменения проекта."""

import ast
from importlib.util import resolve_name
from pathlib import Path

from datamodel_code_generator import (
    DataModelType,
    GenerateConfig,
    InputFileType,
    PythonVersion,
    generate,
)
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from .contracts import ContractError, Contracts, Endpoint

HEADER = "# Generated by tools.codegen. Do not edit."


def templates() -> Environment:
    environment = Environment(
        loader=FileSystemLoader(Path(__file__).parent / "templates"),
        undefined=StrictUndefined,
        autoescape=False,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    environment.filters["py"] = repr
    return environment


def check_handler(source: str, endpoint: Endpoint) -> None:
    """Не заменять ручной код при изменении входной сигнатуры контракта."""
    tree = ast.parse(source)
    function = next(
        (
            node
            for node in tree.body
            if isinstance(node, ast.AsyncFunctionDef) and node.name == endpoint.function
        ),
        None,
    )
    if function is None:
        raise ContractError(
            f"В {endpoint.module} нужна async-функция {endpoint.function}"
        )
    arguments = {arg.arg: arg for arg in function.args.args + function.args.kwonlyargs}
    expected = {}
    if endpoint.has_query:
        expected["query"] = "models.QueryParams"
    if endpoint.body_model:
        expected["body"] = f"models.{endpoint.body_model}"
    for name in {"query", "body"}:
        if (name in expected) != (name in arguments):
            raise ContractError(
                f"{endpoint.module}: изменился параметр {name}; обновите обработчик вручную"
            )
        if name in expected:
            annotation = arguments[name].annotation
            if annotation is None or expected[name] not in {
                ast.unparse(node) for node in ast.walk(annotation)
            }:
                raise ContractError(
                    f"{endpoint.module}: {name} должен использовать {expected[name]}"
                )


def render_models(contracts: Contracts) -> dict[Path, str]:
    if not contracts.specification["components"]["schemas"]:
        return {}
    result = generate(
        contracts.specification,
        config=GenerateConfig(
            input_file_type=InputFileType.OpenAPI,
            output_model_type=DataModelType.PydanticV2BaseModel,
            target_python_version=PythonVersion.PY_312,
            openapi_scopes=["schemas"],
            treat_dot_as_module=True,
            use_exact_imports=True,
            use_subclass_enum=True,
            use_union_operator=True,
            disable_timestamp=True,
            disable_future_imports=True,
            custom_file_header=HEADER,
            formatters=["isort", "black"],
        ),
    )
    if not isinstance(result, dict):
        raise ContractError("Генератор не вернул ожидаемую структуру Python-модулей")
    files = {
        Path(*parts): absolute_model_imports(Path(*parts), code)
        for parts, code in result.items()
    }
    expected = {
        Path(*name.rsplit(".", 1)[0].split(".")).with_suffix(".py")
        for name in contracts.specification["components"]["schemas"]
    }
    missing = expected - files.keys()
    if missing:
        raise ContractError(
            f"Генератор не создал ожидаемые модули: {sorted(map(str, missing))}"
        )
    for path in files:
        if path not in expected and path.name != "__init__.py":
            raise ContractError(f"Неожиданный выходной модуль: {path}")
    return files


def absolute_model_imports(path: Path, code: str) -> str:
    """Импорты генерируемых моделей привязаны к пакету src, а не глубине файла."""
    package = ".".join(("src", *path.parent.parts))
    lines = code.splitlines(keepends=True)
    imports = [
        node
        for node in ast.walk(ast.parse(code))
        if isinstance(node, ast.ImportFrom) and node.level
    ]
    for node in sorted(imports, key=lambda node: node.lineno, reverse=True):
        node.module = resolve_name("." * node.level + (node.module or ""), package)
        node.level = 0
        lines[node.lineno - 1 : node.end_lineno] = [ast.unparse(node) + "\n"]
    return "".join(lines).rstrip() + "\n"


def render_project(
    root: Path, contracts: Contracts
) -> tuple[dict[Path, str], set[Path]]:
    source_root = Path("src")
    generated = {
        source_root / path: code for path, code in render_models(contracts).items()
    }
    create_only = {path for path in generated if path.name == "__init__.py"}
    environment = templates()
    routes = []
    for endpoint in contracts.endpoints:
        handler = source_root / Path(*endpoint.module.split(".")).with_suffix(".py")
        if handler in generated:
            raise ContractError(f"Обработчик конфликтует с файлом моделей: {handler}")
        responses = []
        for status, response in endpoint.operation["responses"].items():
            model = None
            if "content" in response:
                model = response["content"]["application/json"]["schema"][
                    "$ref"
                ].removeprefix("#/schemas/")
            responses.append(
                {
                    "status": int(status),
                    "description": response["description"],
                    "model": model,
                }
            )
        success = next(
            item
            for item in sorted(responses, key=lambda item: item["status"])
            if 200 <= item["status"] < 300
        )
        return_models = [
            response["model"] for response in responses if response["model"]
        ]
        content = environment.get_template("handler.py.jinja").render(
            endpoint=endpoint, return_models=return_models
        )
        if (root / handler).exists():
            check_handler((root / handler).read_text(encoding="utf-8"), endpoint)
        generated[handler] = content
        create_only.add(handler)
        routes.append(
            {
                "endpoint": endpoint,
                "responses": responses,
                "success": success,
                "response_codes_name": "_RESPONSE_CODES_"
                + endpoint.module.removeprefix("views.").replace(".", "_").upper(),
            }
        )
        # Ручка без схем тоже должна иметь импортируемый модуль models.
        models_path = source_root / Path(
            *endpoint.models_module.split(".")
        ).with_suffix(".py")
        generated.setdefault(models_path, HEADER + "\n")
    registry = source_root / "views/_generated_router.py"
    generated[registry] = environment.get_template("router.py.jinja").render(
        routes=routes, header=HEADER
    )
    for path in list(generated):
        for directory in path.parents:
            if directory == source_root.parent:
                break
            init = directory / "__init__.py"
            if init not in generated:
                generated[init] = ""
            create_only.add(init)
    for path, content in generated.items():
        ast.parse(content, filename=str(path))
    return generated, create_only
